# Generated by Django 5.1.3 on 2025-01-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_extracted_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='resume',
        ),
    ]
