# Generated by Django 5.1.6 on 2025-02-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_application_created_at_application_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='perks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='quota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tasks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='timely_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('night', 'Night'), ('flexible', 'Flexible')], default='morning', max_length=50),
        ),
    ]
