version: '3.8'

services:
  web:
    build: .
    container_name: stanfordwork
    depends_on:
      - db
    env_file:
      - .venv
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python stanfordwork.wsgi:application 127.0.0.1 0.0.0.0:8000

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .venv
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
