# Generated by Django 5.1.3 on 2025-01-21 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0007_remove_job_extracted_text_remove_job_posted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_analytics', to='jobs.job')),
            ],
            options={
                'ordering': ['-last_updated_at'],
            },
        ),
    ]
