# Generated by Django 5.1.3 on 2025-01-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_employer_job_is_active_job_salary_job_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AddField(
            model_name='job',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resumes/'),
        ),
    ]
