# Generated by Django 5.1.3 on 2025-01-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPostingAnalytics',
        ),
    ]
